#!/usr/bin/env bash
#RSA by S1M0BH

check_factor()
{
	if [ $# -ne 3 ];
        then
                arg=("$@")
                ct=0
                num2=1
                for a in ${arg[*]};
                do
                        if [ $ct -gt 1 ];
                        then
                                num2=$(echo $a*$num2 | bc)
                        fi
                        ct=$((ct + 1))
                done
        else
                num2=$3
        fi

        num1=$2
        num=$(echo "$1" | tr ':' '=')

        rest=$(echo "if($num2 > $num1) 1 else 0" | bc)
	        if ((rest == 1)); then
		        numcp=$num1
		        num1=$num2
		        num2=$numcp
                fi

        echo "$num$num1*$num2"
}

if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else

        while read i
        do

                rest=$(factor "$i")
                check_factor $rest

        done < "$1"
fi
